### ISSUE TITLE
Allow CF_API_KEY and CF_API_EMAIL as alternative environment variables for Cloudflare

### ISSUE THREAD

**Issue by jleclanche** [caddyserver/dnsproviders#22]
The cloudflare tools use those environment variable names. If caddy can switch, or read from both, then that makes compatibility with those tools easier. :)

https://github.com/cloudflare/python-cloudflare
https://github.com/cloudflare/cloudflare-go/tree/master/cmd/flarectl

**Comment by mholt** [comment]
Hm, yeah, I agree -- but the correct place to file that will be in https://github.com/xenolf/lego -- in fact, if you could just submit a PR, that would be great. :) Checking both kinds of variables would be fine I think. Thanks!

**Comment by jleclanche** [comment]
Filed at https://github.com/xenolf/lego/issues/492

**Comment by liunian1004** [comment]
set shell env:

```
export CF_API_KEY=xxx
export CF_API_EMAIL =xxx
```
