### ISSUE TITLE
Route53 error: failed to load system roots and no roots provided

### ISSUE THREAD

**Issue by matfiz** [caddyserver/dnsproviders#29]
I am trying to use dns challenge (Route53 dns provider). However, when running Caddy, I get an error:

```
making ACME client to get ToS URL: get directory at 'https://acme-v02.api.letsencrypt.org/directory': failed to get json "https://acme-v02.api.letsencrypt.org/directory": Get https://acme-v02.api.letsencrypt.org/directory: x509: failed to load system roots and no roots provided
```

Any ideas?

**Comment by matfiz** [comment]
I have a clue: https://community.letsencrypt.org/t/acme-v2-production-environment-wildcards/55578 in the bottom:

> Breaking Changes
> There is one breaking API change that we have scheduled to remove a protocol divergence introduced recently. By Thursday, March 29th, 2018 all ACME v2 clients will be required to send a Content-Type header with the value application/jose+json for all JWS authenticated POST requests. Please see our API announcement 401 for more information.

Is it supported?

**Comment by mholt** [comment]
Are you using Docker or some sort of odd Linux setup? This error usually happens when the system doesn't have a root certificate store provided, often a misconfiguration.

(Closing, as it _certainly_ isn't an issue in the dnsprovider plugin, but feel free to follow up or ask on our forum!)

**Comment by matfiz** [comment]
I am using Docker, thanks for the tip. I will follow up on forum.
