### ISSUE TITLE
Googlecloud DNS provider won't build

### ISSUE THREAD

**Issue by hasenbanck** [caddyserver/dnsproviders#30]
Googlecloud DNS provider won't build as of right now.

The import github.com/xenolf/lego/providers/dns/googlecloud changed to github.com/xenolf/lego/providers/dns/gcloud 8 days ago.

https://github.com/xenolf/lego/commit/0593b64674aab6828aee3ad05bea55fd0dc2476f

**Comment by mholt** [comment]
Thanks! Do you think you have a moment to submit a pull request? I will be happy to merge it in and deploy an update.
