### ISSUE TITLE
Internal Server Error on caddy download.

### ISSUE THREAD

**Issue by ahmdrz** [caddyserver/dnsproviders#38]
Hi, I have a problem with `godaddy dns`.

I can download `caddy` using `https://caddyserver.com/download/linux/amd64?plugins=http.ratelimit,tls.dns.cloudflare&license=personal&telemetry=off` but I cannot download it with `https://caddyserver.com/download/linux/amd64?plugins=http.ratelimit,tls.dns.cloudflare,tls.dns.godaddy&license=personal&telemetry=off`. It said Internal Server Error.

**Comment by mholt** [comment]
It's working for me. 🤷‍♂️  Try again?
