### ISSUE TITLE
Should use v1 of dnsimple tokens

### ISSUE THREAD

**Issue by ramontayag** [caddyserver/dnsproviders#4]
It wasn't obvious to me, so this might be helpful for others. I kept getting auth errors because I was using the v2 access tokens of DNSimple. Filing an issue here but not sure where you'd like to mention that users ought to use v1.

**Comment by mholt** [comment]
Hm, better yet we should probably start using v2. That'd be an issue for https://github.com/xenolf/lego -- can you file this there? Thanks for reporting!

**Comment by ramontayag** [comment]
There's [a ticket](https://github.com/caddyserver/dnsproviders/issues/4) that will address this.
