### ISSUE TITLE
Add Linode v4 provider

### ISSUE THREAD

**Issue by vborras** [caddyserver/dnsproviders#41]
Hi,

I'm using Linode as a DNS provider and I can't get a wildcard certificate. After some research, I've seen that there's a Linode v4 Lego provider (https://godoc.org/github.com/xenolf/lego/providers/dns/linodev4) and I think maybe that's what I need, but I don't know absolutely anything about Go, so I can't even try it.

I'm not totally sure that's my problem anyway, but it's the most reasonable answer i can come up with.

**Comment by mholt** [comment]
Coincidentally, changes are happening in the core of Caddy right now that could potentially deprecate DNS provider plugins; they would no longer be needed, and instead, [all of lego's DNS providers](https://github.com/xenolf/lego/tree/master/providers/dns) would be supported by default for every Caddy instance without the need for plugins. (The downside is the Caddy binary will grow in size.) 

There's a poll taking place here: https://caddy.community/t/poll-we-can-end-dns-provider-plugins-should-we/4887?u=matt - I would like to get your opinion!

**Comment by vborras** [comment]
Thanks for your reply!

I tried to vote but it seems like the registered and email validation pages in the forum don't work 😬. Anyway, although I haven't used Caddy that much, I would choose whatever improves the maintainability of the project, as in my case the size increase isn't a big deal.

Do you have an ETA for this? Is there any workaround I can use meanwhile?

**Comment by mholt** [comment]
The forum links were fixed, a few people reported problems (Discourse apparently _hard-codes_ the hostname of the forum into the application so I had to rebuild the whole thing). If you can land your vote there now, that'd be great.

The best thing to do for now would be to use old commits that haven't experienced the breaking changes yet, I think.

**Comment by vborras** [comment]
Voted 😄 

The provider I need doesn't even exist, so I guess I'll have to wait for that change. Hope it's soon, but I'm not really in a big hurry.

Thanks for your attention!

**Comment by mholt** [comment]
Thanks! Feel free to submit the change to lego if you need to add a provider.

**Comment by mholt** [comment]
Also the LinodeV4 provider does exist: https://godoc.org/github.com/xenolf/lego/providers/dns/linodev4

**Comment by vborras** [comment]
Yes, the Lego provider exists, but the Caddy provider doesn't. I guess I could give it a try in a few days and submit a PR, but I've never done anything with Go and I'll have to start from the ground.
