### ISSUE TITLE
Cloudflare provider broken by recent lego change

### ISSUE THREAD

**Issue by grugnog** [caddyserver/dnsproviders#43]
Trying to build Caddy using the builder Docker image today I started getting: `../../caddyserver/dnsproviders/cloudflare/cloudflare.go:27:10: undefined: "github.com/xenolf/lego/providers/dns/cloudflare".NewDNSProviderCredentials`

https://github.com/caddyserver/dnsproviders/blob/master/cloudflare/cloudflare.go#L27 seems to have been broken by this lego PR https://github.com/xenolf/lego/pull/700 seems to have broken: NewDNSProviderCredentials has now become NewDNSProviderConfig:
https://github.com/xenolf/lego/commit/42941ccea6b431ebff203d4cb520991fb7b47951#diff-4b4df13aed4b80f0ad1ad61ae2b10788L70

**Comment by grugnog** [comment]
Curiously, https://github.com/mholt/caddy/blob/master/vendor/manifest#L170 is pointing to the lego commit prior to this one, so perhaps the issue is builder (at https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh#L34 maybe) not using the vendor directory somehow?

**Comment by mholt** [comment]
Probably -- /cc @abiosoft

**Comment by abiosoft** [comment]
Yeah, it's not using the vendor directory.

**Comment by grugnog** [comment]
Thanks for taking a look. Closing in favour of https://github.com/abiosoft/caddy-docker/issues/151 which is in the right project :)
