### ISSUE TITLE
Including tls.dns.digitalocean plugin breaks build of Caddy

### ISSUE THREAD

**Issue by mjmare** [caddyserver/dnsproviders#48]
I cannot download a build of Caddy (v0.11.1) with the mentioned plugin. Other plugins work fine.
The error is uninformative: "Oops. Maybe one of the plugins is temporarily broken. Try adjusting which plugins you've selected, or download Caddy from GitHub without any plugins (it will always work!)."

This is the download URL:
```
https://caddyserver.com/download/darwin/amd64?plugins=tls.dns.digitalocean&license=personal&telemetry=off
```
The installer script is:
```
curl https://getcaddy.com | bash -s personal tls.dns.digitalocean
```
hangs without error:
```
curl https://getcaddy.com | bash -s personal tls.dns.digitalocean
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7380  100  7380    0     0  11036      0 --:--:-- --:--:-- --:--:-- 11047
Downloading Caddy for darwin/amd64 (personal license)...
```

This is on MacOS. I had the same problems when trying to download a similar linux build.

**Comment by mholt** [comment]
Hm, yeah, it's about time to do a new release.
