### ISSUE TITLE
No namedotcom providor

### ISSUE THREAD

**Issue by Grygon** [caddyserver/dnsproviders#50]
Despite being listed in this repo, no plugin for namedotcom can be found on https://caddyserver.com/download and even manually linking to https://caddyserver.com/download/linux/amd64?plugins=tls.dns.namedotcom&license=personal&telemetry=on doesn't result in an available build.

Did this get overlooked in a recent release or something? I'm not using name.com anymore, but it's still an odd issue.

**Comment by magikstm** [comment]
It was added recently.

As mentioned here: https://caddy.community/t/username-is-required/5418/6

This issue can be closed.
