### ISSUE TITLE
h2non: uknown revision 000000000000

### ISSUE THREAD

**Issue by mdbraber** [caddyserver/dnsproviders#59]
```
root@acmeproxy:~/src/caddy# go get github.com/caddyserver/dnsproviders@master
go: finding github.com/caddyserver/dnsproviders master
go: finding github.com/h2non/gock v0.0.0-00010101000000-000000000000
go: github.com/h2non/gock@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements
```

When trying to build caddy with the dnsproviders plugins from master I get this error. I see there's a 'replace' statement at the bottom of go.mod but not sure what to do to fix this error @mholt?

**Comment by mdbraber** [comment]
Similar issue found here: https://github.com/mholt/caddy/issues/2598: add `replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14` in your local `go.mod` solves it.

**Comment by mholt** [comment]
See also https://github.com/h2non/gock/issues/50
