### ISSUE TITLE
Can not install godady dns provider

### ISSUE THREAD

**Issue by Sutrain717** [caddyserver/dnsproviders#82]
curl https://getcaddy.com | bash -s personal tls.dns.godaddy

return

curl: (22) The requested URL returned error: 500 Internal Server Error
Aborted, error 22 in command: curl -fsSL "$caddy_url" -u "$CADDY_ACCOUNT_ID:$CADDY_API_KEY" -o "$dl"

**Comment by Splizard** [comment]
Build fails
```
go: github.com/caddyserver/dnsproviders@v0.3.0 requires
        github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by Splizard** [comment]
Can confirm that this fixes the issue
https://github.com/caddyserver/dnsproviders/issues/80#issuecomment-533837957

**Comment by mholt** [comment]
This should be fixed on the build server now.
