### ISSUE TITLE
Cannot "plugin" the Cloudflare provider.

### ISSUE THREAD

**Issue by oxroltd** [caddyserver/dnsproviders#84]
Hello,

I am building the entirety of Caddy from scratch (not just plugging in some plugins). I've seen the other issues (#80) and 

`replace github.com/h2non/gock => gopkg.in/h2non/gock.v1 v1.0.14`

is already in the `go.mod` file of this repository (dnsproviders/cloudflare)
The error is:

```text
go: github.com/caddyserver/dnsproviders@v0.3.0 requires
        github.com/h2non/gock@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

Any ideas? 

Thanks.

**Comment by oxroltd** [comment]
Solved

**Comment by moralrebuild** [comment]
@oxroltd could please tell me how did you solve the issue. I was trying to compile the caddy with the plugin on Archlinux but blocked for this problem.

**Comment by mholt** [comment]
Should be fixed on the build server now.
