### ISSUE TITLE
Clarify for which caddy versions

### ISSUE THREAD

**Issue by zhengqunkoo** [caddyserver/dnsproviders#89]
It is not clear from the `README`s of this repo and [tls.dns](https://github.com/caddyserver/tls.dns), which versions of `caddy` each are for.

I assume [tls.dns](https://github.com/caddyserver/tls.dns) is for `caddy v2`?

**Comment by mholt** [comment]
Yes, that's correct. We'll be phasing out this repo later. But I have more work to do before tls.dns is ready to grow. The underlying lib needs some refactoring before it can meet our requirements.
