### ISSUE TITLE
license

### ISSUE THREAD

**Issue by carlwgeorge** [caddyserver/dnsproviders#9]
What license are these plugins available under?

**Comment by mholt** [comment]
Never thought about it -- probably the same as Caddy itself (Apache 2). I can add a license file in a bit.

Just curious -- as I've always wondered the various reasons why OSS licenses are important to people -- why are you asking?

**Comment by carlwgeorge** [comment]
Fedora packaging policy requires specifying the license.  This is part of my preparation to submit caddy to Fedora.

**Comment by mholt** [comment]
Okay. I guess it's turtles all the way down. :smile: I'll add the license file soon.

**Comment by mholt** [comment]
Done in 8c9fc0487be7ce4d5cfa6f509c58150033eaa23e - I chose MIT because these packages are basically "adapters" and are extremely simple; plus, it doesn't require a (c) statement at the top of every code file.

**Comment by carlwgeorge** [comment]
Thanks!
